### ISSUE TITLE
Get and display attestation JWT when the user navigates to the upload-data page.

### ISSUE THREAD

**Issue by longtomjr** [ntls-io/trusted-compute-web#7]
The JWT should be verified on the frontend, and the results of verification displayed. If verification fails, retry once, and if it still fails, an error page should be displayed to the user.

The relevant values that should be displayed to the user is:
  - x-ms-sgx-mrsigner: hex encoded value of the “mrsigner” field of the quote
  - x-ms-sgx-mrenclave: hex encoded value of the “mrenclave” field of the quote

The user should be able to copy the JWT on the file upload page to allow them to verify the token themselves if needed.

The JWT token should be stored inside of the session state of the application. It probably makes the most sense to store just the token payload.

**Comment by jongbonga** [comment]
@longtomjr what should the error message say?
